config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :home, only:[] do
  	collection do
  		post	:extract_urls_count
  		post	:get_records
  	end
  end
end

app/models/query.rb
class Query < ActiveRecord::Base
	has_many :query_records
	has_many :records, :through => :query_records

	enum status: [:incomplete, :complete]
end

app/models/query_record.rb
class QueryRecord < ActiveRecord::Base
	belongs_to :query
	belongs_to :record
end

app/models/record.rb
class Record < ActiveRecord::Base
	has_many :query_records
	has_many :queries, :through => :query_records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	@@number_of_jobs = 1
	def index
	end

	def extract_urls_count
		if @@number_of_jobs > 2
			render json: false
		else
			@@number_of_jobs = @@number_of_jobs + 1
			@query = Query.create(:query_url => params[:base_url])
			@query.update_attribute(:status, 'incomplete')
			ScrapeForEmailsJob.perform_async(params[:base_url], @query.id)
			# ScrapeForEmailsJob.perform_later(params[:base_url], @query.id)
			render json: @query.id
		end
	end

	def get_records
		render partial: "home/records", locals: { records: Query.find(params[:query_id]).records }
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_records.html.haml
- records.each do |record|
	.col-md-3.bordered-div
		%p= record.email

app/views/home/index.html.haml
.col-md-12
	.form-group.input-group.mt40
		= text_field_tag :url_to_scrape, nil, placeholder: "Enter URL here:", class: "form-control base_url_field"
		= link_to "Extract", "#", class: "btn btn-primary extract-email-button input-group-addon", :"data-url" => extract_urls_count_home_index_path
.col-md-12
	%p.hidden.number-of-links Number of links found: 10
	%p.hidden.processing-status Processing Link Number: 1
	%p 
		Emails:
		= link_to "Refresh", "#", class: "refersh-records", :"data-url" => get_records_home_index_path
	#recors-div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emailscraper</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>